name: Docker Image CI

on:
  push:
    branches:
      - main
      - image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gowthami5j2/mercari-build-training:v1.0 .

      - name: Push Docker image
        run: |
          docker push ghcr.io/gowthami5j2/mercari-build-training:v1.0
